language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
  - "6.0"
  - "7.0"
  - "8.0"
branches:
  only:
    - master
before_install: npm install -g coffee-script
script: npm run-script test-cov
after_success:
  - "test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info"
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token: dc64f5bbd8c050503fb79da6f9abbb694feb1ef8981f7d331c82788821046e90
